### ISSUE TITLE
Error al instalar

### ISSUE THREAD

**Issue by ericertl** [TodoPago/Plugin-opencart2#3]
Tengo opencart 2.2, habilite la extension de soap.
Luego ir a 'extensions->payments' e ir a la opción Todo Pago e instalar, me encuentro con el siguiente error:

Notice: Undefined index: pluginVersion in /home/lauracra/public_html/lauracraft/admin/controller/payment/todopago.php on line 128Notice: Undefined variable: errorMessage in /home/lauracra/public_html/lauracraft/admin/controller/payment/todopago.php on line 131Warning: Cannot modify header information - headers already sent by (output started at /home/lauracra/public_html/lauracraft/admin/controller/startup/error.php:34) in /home/lauracra/public_html/lauracraft/system/library/response.php on line 12

le forze la variable pluginVersion=1.10.0, me dio otro error, pero al parecer se instalo

**Comment by Thargelion** [comment]
Hola @ericertl ¿Otorgaste los permisos al grupo de usuarios Administrator? ¿Qué versión del plugin estás usando?
Saludos!

**Comment by ericertl** [comment]
Instale desde 0 la version 1.10.0. Tenia permisos de administrador. Si te fijas el error: `Undefined variable: errorMessage` te vas a dar cuenta que no es un tema de permisos. De cualquier manera logre instalarlo, pero decidimos no usarlo, ya que la pagina de todopago tambien me tiraba un error cuando queria generar la key de test y nadie me contesto al respecto

**Comment by Thargelion** [comment]
Entonces doy por cerrado el issue. 
Saludos!
